### ISSUE TITLE
Incorrect result of example?

### ISSUE THREAD

**Issue by kzhong130** [menonsamir/spiral#1]
Hi there, thanks a lot for sharing your implementation of spiral. When I tried out running your example using `python3 select_params.py 20 256 --show-output`, it outputs message `Is correct?: 0` which I believe it's from [this line](https://github.com/menonsamir/spiral/blob/main/src/spiral.cpp#L1494). And the message seems to indicate that there are some errors when running the benchmarks? 
I wonder would that be possible to help clarify a bit whether this message indicates an error or can I just safely ignore it?
Thank you!

**Comment by menonsamir** [comment]
By default, the scripts use an implicit database representation that may result in an ‘incorrect result’ output. If you add the flag `--explicit-db` to the run, you should indeed see the ‘correct result’ output.

I should probably update the example to add this flag.

**Comment by kzhong130** [comment]
Got it, thank you!
