### ISSUE TITLE
about more record index

### ISSUE THREAD

**Issue by TY-cc** [menonsamir/spiral#3]
I found the  biggest  record index  is  2^20  in  paper. Can it support  bigger  record? example 2^24 or more?

**Comment by menonsamir** [comment]
This may be possible, especially for SpiralStream / SpiralStreamPack, but this library does not support it yet. If we do add support for this, it will be in the new Rust repo (https://github.com/menonsamir/spiral-rs).

Also, if database records are small in size, then accommodating a larger number of elements is possible as long as you are willing to sacrifice on the rate. For example, we could accomplish serving a 2^24 x 16 byte database by instead using a 2^15 x 8192 byte database, though our response sizes would have to be quite large relative to the actual plaintext size.

**Comment by TY-cc** [comment]
Thanks，I got it.  I have  another problem  on this potorcol about  how to use retireval the value by the keyword
